### ISSUE TITLE
error executing test  convert relion

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-relion#13]
Erro:

[   FAILED ] TestReconstruct.test_reconstRotandShiftFlip

Traceback (most recent call last):
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/site-packages/relion/tests/test_convert_relion.py", line 777, in test_reconstRotandShiftFlip
    self.launchTest('reconstRotandShiftFlip', mList, alignType=ALIGN_PROJ)
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/site-packages/relion/tests/test_convert_relion.py", line 317, in launchTest
    "Different data files:\n>%s\n<%s" % (goldFn, outputFn))
  File "/home/marta/software/scipion_plugin/software/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: Different data files:
>/home/marta/software/scipion_plugin/data/tests/emx/reconstRotandShiftFlip_Gold_output.vol
</home/marta/ScipionUserData/Tests/TestReconstruct/reconstRotandShiftFlip_output.vol

**Comment by azazellochg** [comment]
No branch, no versions, how am I supposed to reproduce that @rmarabini ?

Scipion 2.0 devel-pluginization db8330c
Plugin devel
[ RUN   OK ] TestReconstruct.test_reconstRotandShiftFlip (35.704 secs)
