### ISSUE TITLE
mask radius wizard not setting values

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#145]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/gui/form.py", line 1058, in _showWizard
    wizard.show(self.window)
  File "/home/azazello/soft/scipion-plugins/scipion-em-relion/relion/wizards.py", line 70, in show
    ParticleMaskRadiusWizard.show(self, form, _value, _label, units=self._unit)
  File "/home/azazello/soft/scipion3/scipion-em/pwem/wizards/wizard.py", line 220, in show
    self.setVar(form, label, d.getRadius())
TypeError: getRadius() missing 1 required positional argument: 'radiusSlider'
```

**Comment by azazellochg** [comment]
duplicate of https://github.com/scipion-em/scipion-em/issues/72
