### ISSUE TITLE
Reference picking radius wizard not working

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-relion#156]
Two main problems:
* I think size in pixels and A is wrong. It is showing >100 px when the images are 64px, thus the A size is also wrong
* After accepting the wizard value, it is not properly set in the form

**To Reproduce**
Run a few steps of Relion betagal tutorial and use that wizard for picking with references.

**Expected behavior**
Properly size should be shown and the value set after selected by the user.

**Screenshots**
![image](https://user-images.githubusercontent.com/8441688/77407230-1b6fab00-6db6-11ea-8d47-9ef3aeb5a1c6.png)

**Desktop (please complete the following information):**
 - Scipion version: 3.0 all base plugins in devel branch
 - Relion plugin version: branch python3_migration

**Additional context**

**Comment by delarosatrevin** [comment]
@pconesa @JorMaister I think this is broken after the wizard changes, could you please take a look at this?

**Comment by JorMaister** [comment]
I'll check it out. Thanks, @delarosatrevin

**Comment by delarosatrevin** [comment]
This is the error in the console:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/josem/work/development/scipion3/source/scipion-pyworkflow/pyworkflow/gui/form.py", line 1062, in _showWizard
    wizard.show(self.window)
  File "/home/josem/work/development/scipion3/source/plugins/scipion-em-relion/relion/wizards.py", line 290, in show
    RelionPartMaskDiameterWizard.show(self, form)
  File "/home/josem/work/development/scipion3/source/plugins/scipion-em-relion/relion/wizards.py", line 71, in show
    ParticleMaskRadiusWizard.show(self, form, _value, _label, units=self._unit)
  File "/home/josem/work/development/scipion3/source/scipion-em/pwem/wizards/wizard.py", line 220, in show
    self.setVar(form, label, d.getRadius())
TypeError: getRadius() missing 1 required positional argument: 'radiusSlider'
```

**Comment by delarosatrevin** [comment]
It also happens in relion - initial model protocol, in the particle radius wizard.
