### ISSUE TITLE
conversion error in 3.0

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#177]
I think the imports are somehow wrong, 
```
STARTED: convertInputStep, step 1
  2020-06-05 21:36:33.756859
Traceback (most recent call last):
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 188, in run
    self._run()
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 239, in _run
    resultFiles = self._runFunc()
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 235, in _runFunc
    return self._func(*self._args)
  File "/home/azazello/soft/scipion-plugins/scipion-em-relion/relion/protocols/protocol_expand_symmetry.py", line 66, in convertInputStep
    convert.writeSetOfParticles(
  File "/home/azazello/soft/scipion-plugins/scipion-em-relion/relion/convert/__init__.py", line 82, in writeSetOfParticles
    return createWriter(**kwargs).writeSetOfParticles(imgSet, starFile, **kwargs)
AttributeError: 'Reader' object has no attribute 'writeSetOfParticles'
Protocol failed: 'Reader' object has no attribute 'writeSetOfParticles'
FAILED: convertInputStep, step 1
```

Any ideas, @delarosatrevin ?

**Comment by delarosatrevin** [comment]
Fixed in c088aea
