### ISSUE TITLE
TestRelionWriter.test_particlesToStar fail

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#179]
```
[   FAILED ] TestRelionWriter.test_particlesToStar

Traceback (most recent call last):
  File "/home/azazello/.conda/envs/.scipion3env/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/azazello/.conda/envs/.scipion3env/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/azazello/.conda/envs/.scipion3env/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/azazello/soft/scipion-plugins/scipion-em-relion/relion/tests/test_convert_relion.py", line 747, in test_particlesToStar
    starWriter.writeSetOfParticles(outputParts, outputStar)
  File "/home/azazello/soft/scipion-plugins/scipion-em-relion/relion/convert/convert31.py", line 302, in writeSetOfParticles
    opticsTable.addRow(**opticsDict)
  File "/home/azazello/soft/scipion-plugins/scipion-em-relion/relion/convert/metadata.py", line 328, in addRow
    self._rows.append(self.Row(*args, **kwargs))
TypeError: __new__() got an unexpected keyword argument 'rlnMtfFileName'
```

**Comment by delarosatrevin** [comment]
Fixed in 3e7667a
