### ISSUE TITLE
Some recursion issue when scheduling (in Scipion) a Relion 3D refine 

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-relion#2]
Probably it is a more general issue, but detected with this protocol.
The issue has been detected in release-1.2.1, but will not be addressed there.

>>>>> python  /home/josem/work/development/scipion/pyworkflow/apps/pw_schedule_run.py "/home/josem/ScipionUserData/projects/t20-tutorial" "Runs/001870_ProtRelionRefine3D/logs/run.db" "1870"
Error trying to update protocol: (jobId=5662)
 ERROR: maximum recursion depth exceeded while calling a Python object, tries=0
Error trying to update protocol: (jobId=5662)
 ERROR: maximum recursion depth exceeded while calling a Python object, tries=1
Error trying to update protocol: (jobId=5662)
 ERROR: maximum recursion depth exceeded while calling a Python object, tries=2
Error trying to update protocol: (jobId=5662)
 ERROR: maximum recursion depth exceeded while calling a Python object, tries=3
Traceback (most recent call last):
  File "/home/josem/work/development/scipion/pyworkflow/project.py", line 522, in _updateProtocol
    protocol.getObjId())
  File "/home/josem/work/development/scipion/pyworkflow/protocol/protocol.py", line 1972, in getProtocolFromDb
    protocol = project.getProtocol(protId)
  File "/home/josem/work/development/scipion/pyworkflow/project.py", line 972, in getProtocol
    protocol = self.mapper.selectById(protId)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 187, in selectById
    self.fillObject(obj, objRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 245, in fillObject
    self.fillObjectWithRow(childObj, childRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 214, in fillObjectWithRow
    objValue = self.selectById(int(objValue))
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 187, in selectById
    self.fillObject(obj, objRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 245, in fillObject
    self.fillObjectWithRow(childObj, childRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 214, in fillObjectWithRow
    objValue = self.selectById(int(objValue))
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 187, in selectById
    self.fillObject(obj, objRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 245, in fillObject
    self.fillObjectWithRow(childObj, childRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 214, in fillObjectWithRow
    objValue = self.selectById(int(objValue))
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 187, in selectById
    self.fillObject(obj, objRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 245, in fillObject
    self.fillObjectWithRow(childObj, childRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 214, in fillObjectWithRow
    objValue = self.selectById(int(objValue))
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 187, in selectById
    self.fillObject(obj, objRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 245, in fillObject
    self.fillObjectWithRow(childObj, childRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 214, in fillObjectWithRow
    objValue = self.selectById(int(objValue))
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 187, in selectById
    self.fillObject(obj, objRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 245, in fillObject
    self.fillObjectWithRow(childObj, childRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 214, in fillObjectWithRow
    objValue = self.selectById(int(objValue))
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 187, in selectById
    self.fillObject(obj, objRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 245, in fillObject
    self.fillObjectWithRow(childObj, childRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 214, in fillObjectWithRow
    objValue = self.selectById(int(objValue))
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 187, in selectById
    self.fillObject(obj, objRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 245, in fillObject
    self.fillObjectWithRow(childObj, childRow)
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 214, in fillObjectWithRow
    objValue = self.selectById(int(objValue))
  File "/home/josem/work/development/scipion/pyworkflow/mapper/sqlite.py", line 185, in selectById
    obj = self._buildObjectFromClass(objRow['classname'])
  File "/home/josem/work/development/scipion/pyworkflow/mapper/mapper.py", line 80, in _buildObjectFromClass
    instance = self.dictClasses[className](**kwargs)
  File "/home/josem/work/development/scipion/pyworkflow/em/packages/motioncorr/protocol_motioncorr.py", line 67, in __init__
    ProtAlignMovies.__init__(self, **args)
  File "/home/josem/work/development/scipion/pyworkflow/em/protocol/protocol_movies.py", line 61, in __init__
    ProtPreprocessMicrographs.__init__(self, **kwargs)
  File "/home/josem/work/development/scipion/pyworkflow/em/protocol/protocol.py", line 55, in __init__
    Protocol.__init__(self, **kwargs)
  File "/home/josem/work/development/scipion/pyworkflow/protocol/protocol.py", line 324, in __init__
    self._definition = Form(self)
  File "/home/josem/work/development/scipion/pyworkflow/protocol/params.py", line 203, in __init__
    self.addGeneralSection()
  File "/home/josem/work/development/scipion/pyworkflow/protocol/params.py", line 322, in addGeneralSection
    help='The <resume> mode will try to start the execution'
  File "/home/josem/work/development/scipion/pyworkflow/protocol/params.py", line 234, in addParam
    return self.lastSection.addParam(*args, **kwargs)
  File "/home/josem/work/development/scipion/pyworkflow/protocol/params.py", line 135, in addParam
    param = ParamClass(**kwargs)
  File "/home/josem/work/development/scipion/pyworkflow/protocol/params.py", line 411, in __init__
    IntParam.__init__(self, **args)
  File "/home/josem/work/development/scipion/pyworkflow/protocol/params.py", line 398, in __init__
    Param.__init__(self, paramClass=Integer, **args)
  File "/home/josem/work/development/scipion/pyworkflow/protocol/params.py", line 87, in __init__
    FormElement.__init__(self, **args)
  File "/home/josem/work/development/scipion/pyworkflow/protocol/params.py", line 40, in __init__
    OrderedObject.__init__(self, **args)
  File "/home/josem/work/development/scipion/pyworkflow/object.py", line 531, in __init__
    Object.__init__(self, value, **kwargs)
  File "/home/josem/work/development/scipion/pyworkflow/object.py", line 49, in __init__
    self._objIsPointer = kwargs.get('objIsPointer', False) # True if will be treated as a reference for storage
  File "/home/josem/work/development/scipion/pyworkflow/object.py", line 550, in __setattr__
    issubclass(value.__class__, Object) and
RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by delarosatrevin** [comment]
@azazellochg, have you seen this? Maybe we can close it and re-open if we need so.

**Comment by azazellochg** [comment]
I did, with 1.2.x, it happens rarely...

**Comment by azazellochg** [comment]
https://github.com/I2PC/scipion/issues/547 same?

**Comment by delarosatrevin** [comment]
It is happening over here quite frequently..."Wait for" seems to be the common factor when it appears...
