### ISSUE TITLE
3d cls failed

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#220]
Reported by Marcos Gragera

Hi all! I had this error message when doing a 3D classification with particles and initial model from a previous 3D auto-refine. Both 3D classification and auto-refine were performed in relion 3.1 within scipion (devel branch and updated)

the bug happens when "Consider previous alignment? " and "Consider alignment as priors?" are both YES. If "Consider alignment as priors?" is set to NO, the protocol works fine

```
00001:   RUNNING PROTOCOL -----------------
00002:   Hostname: torvalds
00003:   PID: 2672
00004:   pyworkflow: 3.0.4
00005:   plugin: relion
00006:   currentDir: /data/mgragera/cftornero_polI
00007:   workingDir: Runs/010532_ProtRelionClassify3D
00008:   runMode: Restart
00009:             MPI: 2
00010:         threads: 1
00011:    Starting at step: 1
00012:    Running steps
00013:   STARTED: convertInputStep, step 1, time 2020-09-22 11:55:57.786501
00014:   Converting set from 'Runs/010401_ProtRelionRefine3D/particles.sqlite' into 'Runs/010532_ProtRelionClassify3D/input_particles.star'
00015:   convertBinaryFiles: creating soft links.
00016:      Root: Runs/010532_ProtRelionClassify3D/extra/input -> Runs/010058_ProtRelionExtractParticles/extra
00017:   Traceback (most recent call last):
00018:     File "/home/mgragera/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 188, in run
00019:       self._run()
00020:     File "/home/mgragera/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 239, in _run
00021:       resultFiles = self._runFunc()
00022:     File "/home/mgragera/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 235, in _runFunc
00023:       return self._func(*self._args)
00024:     File "/home/mgragera/.conda/envs/.scipion3env/lib/python3.8/site-packages/relion/protocols/protocol_base.py", line 797, in convertInputStep
00025:       mdOptics.writeStar(imgStar, tableName='optics')
00026:     File "/home/mgragera/.conda/envs/.scipion3env/lib/python3.8/site-packages/emtable/metadata.py", line 358, in writeStar
00027:       writer.writeTableName(tableName)
00028:     File "/home/mgragera/.conda/envs/.scipion3env/lib/python3.8/site-packages/emtable/metadata.py", line 243, in writeTableName
00029:       self._file.write("\ndata_%s\n\n" % (tableName or ''))
00030:   AttributeError: 'str' object has no attribute 'write'
00031:   Protocol failed: 'str' object has no attribute 'write'
00032:   FAILED: convertInputStep, step 1, time 2020-09-22 11:58:49.402125
00033:   *** Last status is failed
00034:   ------------------- PROTOCOL FAILED (DONE 1/3)
```

**Comment by azazellochg** [comment]
bug confirmed
