### ISSUE TITLE
Bayesian polishing with EER file format.

### ISSUE THREAD

**Issue by DmitrySemchonok** [scipion-em/scipion-em-relion#359]
**Describe the bug**
When running the relion- bayesian polishing, the process crashes.
Original files are in EER format. 

**To Reproduce**
Steps to reproduce the behaviour:
0. run the bayesian polishing training  with default 10 000 particles and use the parameters for the bayesian polishing
In my case 
Output params:
    Sigma for velocity: 1.140
    Sigma for divergence: 2745.0
    Sigma for acceleration: 3.00

1. Bayesian polishing protocol: Set as the input motion-movie alignment files. I used motioncor plugin v: 3.7
2. Use the setting from step 0.
3. Keep the other parameters as default
4. Set any parameters of Thread/MPI that your system allows. (I tested most of the combinations including Threads = 1, MPI = 1)
5. Click on 'Execute'
6. The process starts normally.
7. After some time - get an error.

**Expected behavior**
Bayesian polishing protocol to finish without errors.

**Screenshots**
If applicable
<img width="2213" alt="Screenshot 2022-09-13 at 09 42 05" src="https://user-images.githubusercontent.com/21281315/189841015-1e66f094-d85a-460b-bd03-fc6f3337e0d6.png">

**Logs**
Attach run.stderr log file from the failing protocol.
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 202, in run
    self._run()
  File "/home/user/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 253, in _run
    resultFiles = self._runFunc()
  File "/home/user/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 249, in _runFunc
    return self._func(*self._args)
  File "/home/user/miniconda3/envs/scipion3/lib/python3.8/site-packages/relion/protocols/protocol_bayesian_polishing.py", line 371, in trainOrPolishStep
    self.runJob(self._getProgram('relion_motion_refine'), args)
  File "/home/user/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1475, in runJob
    self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
  File "/home/user/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 65, in runJob
    process.runJob(log, programName, params,
  File "/home/user/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 55, in runJob
    return runCommand(command, env, cwd)
  File "/home/user/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 70, in runCommand
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
  File "/home/user/miniconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' mpirun -np 5  `which relion_motion_refine_mpi` --i Runs/003535_ProtRelionBayesianPolishing/input_particles.star --o Runs/003535_ProtRelionBayesianPolishing/extra --f Runs/003232_ProtRelionPostprocess/extra/postprocess.star --angpix_ref 0.45450 --corr_mic Runs/003535_ProtRelionBayesianPolishing/input_corrected_micrographs.star --first_frame 1 --last_frame 0 --s_vel 1.140 --s_div 2745.000 --s_acc 3.000 --bfac_minfreq 20.000 --bfac_maxfreq -1.000 --combine_frames --j 5 ' returned non-zero exit status 139.
 [31mProtocol failed: Command ' mpirun -np 5  `which relion_motion_refine_mpi` --i Runs/003535_ProtRelionBayesianPolishing/input_particles.star --o Runs/003535_ProtRelionBayesianPolishing/extra --f Runs/003232_ProtRelionPostprocess/extra/postprocess.star --angpix_ref 0.45450 --corr_mic Runs/003535_ProtRelionBayesianPolishing/input_corrected_micrographs.star --first_frame 1 --last_frame 0 --s_vel 1.140 --s_div 2745.000 --s_acc 3.000 --bfac_minfreq 20.000 --bfac_maxfreq -1.000 --combine_frames --j 5 ' returned non-zero exit status 139. [0m

**Desktop (please complete the following information):**
 - Scipion version: v3.0.11-Eugenios - 3.0.25
 - Relion plugin version 4.0.8

**Additional context**

**Comment by azazellochg** [comment]
Thank you for the report @DmitrySemchonok . I will need more information:
1) first 100 lines of Runs/003535_ProtRelionBayesianPolishing/input_corrected_micrographs.star
2) you didnt attach the **complete** run.stderr

**Comment by DmitrySemchonok** [comment]
> Thank you for the report @DmitrySemchonok . I will need more information:
> 
>     1. first 100 lines of Runs/003535_ProtRelionBayesianPolishing/input_corrected_micrographs.star
> 
>     2. you didnt attach the **complete** run.stderr



Because the website does not accept loading the file type.
I will add it additionally.


<img width="835" alt="Screenshot 2022-09-13 at 10 16 10" src="https://user-images.githubusercontent.com/21281315/189848669-6f8cf6ef-7d29-4ee7-810c-f43fb3de819f.png">

**Comment by azazellochg** [comment]
The file can be renamed to txt

**Comment by DmitrySemchonok** [comment]
> The file can be renamed to txt

[run.txt](https://github.com/scipion-em/scipion-em-relion/files/9554886/run.txt)

**Comment by azazellochg** [comment]
thanks!
1) it looks like you have not run assign optics protocol, hence you are missing the gain reference which is required for EER data.
2) my mistake, I keep forgetting that stderr will not have stdout lines...

**Comment by azazellochg** [comment]
Could you post 100 lines of Runs/003535_ProtRelionBayesianPolishing/input/GridSquare_1783832_Data_FoilHole_5969362_Data_5966229_5966231_20220906_180402_EER.star ? Maybe the gain is there?

**Comment by azazellochg** [comment]
Also, could you attach stdout as well please?

**Comment by DmitrySemchonok** [comment]
> Could you post 100 lines of Runs/003535_ProtRelionBayesianPolishing/input/GridSquare_1783832_Data_FoilHole_5969362_Data_5966229_5966231_20220906_180402_EER.star ? Maybe the gain is there?
[GridSquare_1783832_Data_FoilHole_5969362_Data_5966229_5966231_20220906_180402_EER.txt](https://github.com/scipion-em/scipion-em-relion/files/9556487/GridSquare_1783832_Data_FoilHole_5969362_Data_5966229_5966231_20220906_180402_EER.txt)

**Comment by DmitrySemchonok** [comment]
> Also, could you attach stdout as well please?

[run_out.txt](https://github.com/scipion-em/scipion-em-relion/files/9556494/run_out.txt)

**Comment by azazellochg** [comment]
@DmitrySemchonok 
1) you need to run assign optics protocol on the movies produced by mc2 protocol and set the gain reference correctly.
2) considering that it worked for 3h and not crashed immediately, it might be smth else.

**Comment by azazellochg** [comment]
Worked after the gain was assigned.
