### ISSUE TITLE
Import particles fails

### ISSUE THREAD

**Issue by rsanchezgarc** [scipion-em/scipion-em-relion#388]
**Describe the bug**
 I am trying to import the particles from EMPIAR-10280 on a newly installed scipion version but it does not work, as it fallbacks to a deprecated convert. I am attaching the head -n 300 of the starfile.

**To Reproduce**
Just using the protocol as shown in the picture with the EMPIAR-10280 data

![image](https://github.com/scipion-em/scipion-em-relion/assets/27857332/d01a846e-f3ac-4b46-8b17-2b34f3aac373)

**Screenshots**

**Logs**

Traceback (most recent call last):
  File "/homes/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 204, in run
    self._run()
  File "/homes/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 255, in _run
    resultFiles = self._runFunc()
  File "/homes/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 251, in _runFunc
    return self._func(*self._args)
  File "/homes/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/pwem/protocols/protocol_import/particles.py", line 225, in importParticlesStep
    ci.importParticles()
  File "/homes/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/relion/convert/dataimport.py", line 111, in importParticles
    readSetOfParticles(
  File "/homes/sanchezg/app/miniconda3/envs/scipion3/lib/python3.8/site-packages/relion/convert/convert_deprecated.py", line 463, in readSetOfParticles
    imgMd = md.MetaData(filename)
TypeError: MetaData() takes 0 positional arguments but 1 was given
Protocol failed: MetaData() takes 0 positional arguments but 1 was given

**Desktop (please complete the following information):**
scipion-app==3.1.0
scipion-em==3.1.0
scipion-em-relion==4.0.17
scipion-pyworkflow==3.1.1
RELION version: 4.0.1-commit-0b03a6 

**Additional context**
[smallStar.zip](https://github.com/scipion-em/scipion-em-relion/files/12311761/smallStar.zip)

**Comment by azazellochg** [comment]
Hi @rsanchezgarc , sorry, somehow this issue has slipped away from me. 
```TypeError: MetaData() takes 0 positional arguments but 1 was given``` means that you do not have xmipp installed and it's reverting to a ghost function.

**Comment by azazellochg** [comment]
With xmipp installed I can successfully import your star file

**Comment by rsanchezgarc** [comment]
That is the issue, that xmipp is not a dependency according to the setup.py, isn't it?

**Comment by azazellochg** [comment]
you cannot really do SPA in Scipion without xmipp (tomo is a bit more flexible). Have a look here: https://github.com/search?q=repo%3Ascipion-em%2Fscipion-em%20emlib&type=code

**Comment by rsanchezgarc** [comment]
Got it, thanks
