### ISSUE TITLE
plot cls distr over iterations

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#399]
Does not work for vdam cls 2d:
```
Traceback (most recent call last):
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
return self.func(*args)
File "/public/EM/Scipion/scipion-dev/scipion-pyworkflow/pyworkflow/gui/form.py", line 1229, in _visualizeVar
self.visualizeCallback(self.paramName)
File "/public/EM/Scipion/scipion-dev/scipion-pyworkflow/pyworkflow/viewer.py", line 276, in _visualizeParam
views = self._getVisualizeDict()[paramName](paramName)
File "/public/EM/Scipion/scipion-dev/scipion-em-plugins/scipion-em-relion/relion/viewers/viewer_base.py", line 405, in _plotClassDistribution
table = Table(fileName=modelStar, tableName='model_classes')
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/site-packages/emtable/metadata.py", line 351, in __init__
self.read(fileName, tableName, **kwargs)
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/site-packages/emtable/metadata.py", line 388, in read
with open(fileName) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Runs/000939_ProtRelionClassify2D/extra/relion_it001_model.star'
```

**Comment by azazellochg** [comment]
class3d SSNR plot:
```
Exception in Tkinter callback
Traceback (most recent call last):
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
return self.func(*args)
File "/public/EM/Scipion/scipion-dev/scipion-pyworkflow/pyworkflow/gui/form.py", line 1229, in _visualizeVar
self.visualizeCallback(self.paramName)
File "/public/EM/Scipion/scipion-dev/scipion-pyworkflow/pyworkflow/viewer.py", line 276, in _visualizeParam
views = self._getVisualizeDict()[paramName](paramName)
File "/public/EM/Scipion/scipion-dev/scipion-em-plugins/scipion-em-relion/relion/viewers/viewer_base.py", line 649, in _showSSNR
a = xplotter.createSubPlot(plot_title, 'Angstroms^-1', 'log(SSNR)')
File "/public/EM/Scipion/scipion-dev/scipion-pyworkflow/pyworkflow/gui/plotter.py", line 150, in createSubPlot
a = self.figure.add_subplot(self.gridx, self.gridy, pos, projection=projection)
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/site-packages/matplotlib/figure.py", line 772, in add_subplot
ax = subplot_class_factory(projection_class)(self, *args, **pkw)
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/site-packages/matplotlib/axes/_subplots.py", line 36, in __init__
self.set_subplotspec(SubplotSpec._from_subplot_args(fig, args))
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/site-packages/matplotlib/gridspec.py", line 597, in _from_subplot_args
gs = GridSpec._check_gridspec_exists(figure, rows, cols)
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/site-packages/matplotlib/gridspec.py", line 225, in _check_gridspec_exists
return GridSpec(nrows, ncols, figure=figure)
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/site-packages/matplotlib/gridspec.py", line 385, in __init__
super().__init__(nrows, ncols,
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/site-packages/matplotlib/gridspec.py", line 49, in __init__
raise ValueError(
ValueError: Number of rows must be a positive integer, not 2.5
```
