### ISSUE TITLE
relion Motioncorcreate output error

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-relion#50]
This is coming from:
Weng M Ng
DPhil Student
Huiskonen & Bowden Groups

Division of Structural Biology
Wellcome Trust Centre for Human Genetics
Nuffield Department of Clinical Medicine
University of Oxford

(I'll point him here)

Conversation:

Hi,

> I'm currently experiencing error while running relion motioncor within Scipion v1.2.2-rc (Constantino). I have repeated it 4 times but each time it failed at the same place (%block not found). I do not understand the error message and wonder if you can help me to decipher what I have done wrong? I have attached the log file here. I appreciate any help or comment that you can give.
> 
> Many thanks,
>Weng M Ng 

stdout:
```
  30/  30 sec ............................................................~~(,_,">
 Done! Written: output/logfile.pdf and output/corrected_micrographs.star
Erasing.....movieFolder: Runs/006287_ProtRelionMotioncor/tmp/movie_000010
[35mFINISHED[0m: processMovieStep, step 11
  2019-03-18 16:57:05.662908
Traceback (most recent call last):
  File "/gpfs2/well/strubi/juha/apps/scipion-1.2.1.facilities-relion-3.0/pyworkflow/protocol/protocol.py", line 190, in run
    self._run()
  File "/gpfs2/well/strubi/juha/apps/scipion-1.2.1.facilities-relion-3.0/pyworkflow/protocol/protocol.py", line 1148, in _run
    self._runSteps(startIndex)
  File "/gpfs2/well/strubi/juha/apps/scipion-1.2.1.facilities-relion-3.0/pyworkflow/protocol/protocol.py", line 1019, in _runSteps
    self._stepsCheck)
  File "/gpfs2/well/strubi/juha/apps/scipion-1.2.1.facilities-relion-3.0/pyworkflow/protocol/executor.py", line 124, in runSteps
    stepsCheckCallback()
  File "/gpfs2/well/strubi/juha/apps/scipion-1.2.1.facilities-relion-3.0/pyworkflow/em/protocol/protocol_movies.py", line 245, in _stepsCheck
    self._checkNewOutput()
  File "/gpfs2/well/strubi/juha/apps/scipion-1.2.1.facilities-relion-3.0/pyworkflow/em/protocol/protocol_align_movies.py", line 188, in _checkNewOutput
    newMovie = self._createOutputMovie(movie)
  File "/gpfs2/well/strubi/juha/apps/scipion-1.2.1.facilities-relion-3.0/pyworkflow/em/packages/relion/protocol_motioncor.py", line 399, in _createOutputMovie
    tableName='local_motion_model')
  File "/gpfs2/well/strubi/juha/apps/scipion-1.2.1.facilities-relion-3.0/pyworkflow/em/packages/relion/metadata.py", line 58, in __init__
    self.read(fileName, tableName)
  File "/gpfs2/well/strubi/juha/apps/scipion-1.2.1.facilities-relion-3.0/pyworkflow/em/packages/relion/metadata.py", line 110, in read
    self.readStar(f, tableName)
  File "/gpfs2/well/strubi/juha/apps/scipion-1.2.1.facilities-relion-3.0/pyworkflow/em/packages/relion/metadata.py", line 84, in readStar
    self._findDataLine(inputFile, dataStr)
  File "/gpfs2/well/strubi/juha/apps/scipion-1.2.1.facilities-relion-3.0/pyworkflow/em/packages/relion/metadata.py", line 230, in _findDataLine
    raise Exception("%s block was not found")
Exception: %s block was not found
[32m------------------- PROTOCOL FAILED (DONE 11/2330)[0m
```

Pablo (me)

> Hi Weng, certainly it seems a metadata parsing error.
> I'm sure Jose Miguel will be able to help.
> Meanwhile....it seems there is a parsing error of the metadata file:
> corrected_micrographs.star
> Could you attach it, please?

Weng

> Hi Pablo,
> It failed every time after the ten were written.
> I have attached the ten corrected_micrographs.star that the job has written.
> Many thanks,
> Weng

He attached all starfiles, I'm pasting one:

```
# RELION; version 3.0-alpha-5

data_

loop_ 
_rlnMicrographNameNoDW #1 
_rlnMicrographName #2 
_rlnMicrographMetadata #3 
_rlnAccumMotionTotal #4 
_rlnAccumMotionEarly #5 
_rlnAccumMotionLate #6 
output/FoilHole_4022490_Data_4024375_4024376_20161104_1154-204444_noDW.mrc output/FoilHole_4022490_Data_4024375_4024376_20161104_1154-204444.mrc output/FoilHole_4022490_Data_4024375_4024376_20161104_1154-204444.star    11.864687     0.391054    11.473633 
```

I've replied this:

> Thanks Weng!
> I haven't developed relion code but it seems there is no "block" in the star file.
>
>Code is expecting to find "local_motion_model" inside the star file and I fail to locate that block in your relion star files:
>
># RELION; version 3.0-alpha-5
>
>data_
>
> loop_
> _rlnMicrographNameNoDW #1
> _rlnMicrographName #2
> _rlnMicrographMetadata #3
> _rlnAccumMotionTotal #4
> _rlnAccumMotionEarly #5
> _rlnAccumMotionLate #6
> output/FoilHole_4022490_Data_4024375_4024376_20161104_1154-204444_noDW.mrc  output/FoilHole_4022490_Data_4024375_4024376_20161104_1154-204444.mrc output/FoilHole_4022490_Data_4024375_4024376_20161104_1154-204444.star    11.864687     0.391054    11.473633
>
> As you can see the star file has only one block and is called "data_"
> Now...there could be 2 reasons:
>
> A.- Scipion code should expect the "_data" block.
> B.- Since you are using alpha-5, maybe this has changed in the latest versions and the block is not named data_ anymore.
>
> One option you could try is to update your code to see if that has changed, additionally you will get all the fixes and a relion stable version.
>
>
>Based on relion code that block is written is there is a "model"?
>https://github.com/3dem/relion/blob/600499f35c721e2009135ee027078e69414f7edb/src/micrograph_model.cpp#L219
>
>
>Hope Jose Miguel can give more hints.

**Comment by azazellochg** [comment]
I assigned @delarosatrevin since he is supporting Scipion v1.2.2-rc branch

**Comment by delarosatrevin** [comment]
Yes, I will check it in both my branch and the plug-in.

**Comment by delarosatrevin** [comment]
It is working fine after updating to the most recent version.
